easy_admin:
    site_name: 'Blog'
    entities:
        Post:
            class: App\Entity\Post
            list:
                fields:
                    - 'id'
                    - 'published'
                    - { property: 'publishedAt', format: 'Y/n/j H:i:s' }
                    - 'title'
                    - 'slug'
                    - 'summary'
                    - 'tags'
                    - { property: 'tags', type: 'array' }
                    - { property: 'image', type: 'image', base_path: '%app.path.post_images%' }
            form:
                fields:
                    - 'published'
                    - { type: 'section', label: 'Title' }
                    - 'title'
                    - 'slug'
                    - { type: 'section', label: 'Content' }
                    - 'summary'
                    - 'content'
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'tags', type_options: { expanded: true, multiple: true } }
        Comment:
            class: App\Entity\Comment
        Tag:
            class: App\Entity\Tag
            label: 'Tag'
            list:
                title: "Most recent tags"
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
